//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Answers')
export class AnswersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  answerId: number;

  @Column('integer', { nullable: true })
  questionId: number;

  @Column('text', { nullable: true })
  content: string;

  @Column('text', { nullable: true })
  explanation: string;

  @Column('date', { nullable: true })
  dateCreated: Date;
}
