//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Questions')
export class QuestionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  questionId: number;

  @Column('text', { nullable: true })
  content: string;

  @Column('integer', { nullable: true })
  category: number;

  @Column('integer', { nullable: true })
  difficultyLevel: number;

  @Column('date', { nullable: true })
  dateCreated: Date;
}
