//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  QuestionsList,
  QuestionsCreate,
  QuestionsEdit,
} from './resources/Questions';
import { AnswersList, AnswersCreate, AnswersEdit } from './resources/Answers';
import {
  CategoriesList,
  CategoriesCreate,
  CategoriesEdit,
} from './resources/Categories';
import {
  DifficultyLevelsList,
  DifficultyLevelsCreate,
  DifficultyLevelsEdit,
} from './resources/DifficultyLevels';
import QuestionsIcon from '@mui/icons-material/QuestionAnswer';
import AnswersIcon from '@mui/icons-material/QuestionAnswer';
import CategoriesIcon from '@mui/icons-material/Category';
import DifficultyLevelsIcon from '@mui/icons-material/SignalCellularAlt';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a0df27142">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Questions"
          options={{ label: 'Questions' }}
          list={QuestionsList}
          create={QuestionsCreate}
          edit={QuestionsEdit}
          recordRepresentation="content"
          icon={QuestionsIcon}
        />
        <Resource
          name="Answers"
          options={{ label: 'Answers' }}
          list={AnswersList}
          create={AnswersCreate}
          edit={AnswersEdit}
          recordRepresentation="content"
          icon={AnswersIcon}
        />
        <Resource
          name="Categories"
          options={{ label: 'Categories' }}
          list={CategoriesList}
          create={CategoriesCreate}
          edit={CategoriesEdit}
          recordRepresentation="name"
          icon={CategoriesIcon}
        />
        <Resource
          name="DifficultyLevels"
          options={{ label: 'Difficulty Levels' }}
          list={DifficultyLevelsList}
          create={DifficultyLevelsCreate}
          edit={DifficultyLevelsEdit}
          recordRepresentation="name"
          icon={DifficultyLevelsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
